export const ACTION_TYPES = {
    //Categories
    GET_CATEGORIES: "GET_CATEGORIES",
    
    //SubCategories
    GET_SUB_CATEGORIES: "GET_SUB_CATEGORIES",

    //software
    GET_SOFTWARES: "GET_SOFTWARES",
    GET_FILTERED_SOFTWARES: "GET_FILTERED_SOFTWARES",
    UPDATE_FILTERED_SOFTWARES: "UPDATE_FILTERED_SOFTWARES",
    GET_SINGLE_SOFTWARES: "GET_SINGLE_SOFTWARES",

    //claimed software
    ADD_CLAIMED_SOFTWARE: "ADD_CLAIMED_SOFTWARE",
    GET_HOSTED_CHECKOUT_DATA: "GET_HOSTED_CHECKOUT_DATA",
    GET_SINGLE_USER_CLAIMED_SOFTWARES: "GET_SINGLE_USER_CLAIMED_SOFTWARES",
    GET_WIDGET: "GET_WIDGET",

    //FeedBack
    ADD_FEEDBACK_OF_A_SOFTWARE: "ADD_FEEDBACK_OF_A_SOFTWARE",
    GET_LATEST_REVIEWS: "GET_LATEST_REVIEWS",
    GET_USERS_REVIEWS_COUNT: "GET_USERS_REVIEWS_COUNT",
    GET_USERS_REVIEWS: "GET_USERS_REVIEWS",
    
    //Users
    GET_UNAPPROVED_USERS: "GET_UNAPPROVED_USERS",
    GET_DEACTIVATE_USERS: "GET_DEACTIVATE_USERS",
    UPDATE_USER_STATUS: "UPDATE_USER_STATUS",
    GET_SINGLE_USER: "GET_SINGLE_USER",

    //progress
    PROGRESS_BAR_STATE: "PROGRESS_BAR_STATE",

    //login
    LOGIN: "LOGIN"
}